workspace(name = "tutorial")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_tweag_rules_haskell",
    strip_prefix = "rules_haskell-0.8",
    urls = ["https://github.com/tweag/rules_haskell/archive/v0.8.tar.gz"],
    sha256 = "431d492a8ee6a110cdf42496181c9d27225dfb997379e64a148eb8e69f272ab7",
)

load("@io_tweag_rules_haskell//haskell:repositories.bzl", "haskell_repositories")

haskell_repositories()

http_archive(
    name = "io_tweag_rules_nixpkgs",
    strip_prefix = "rules_nixpkgs-0.5.2",
    urls = ["https://github.com/tweag/rules_nixpkgs/archive/v0.5.2.tar.gz"],
    sha256 = "5a384daa57b49abf9f0b672852f1a66a3c52aecf9d4d2ac64f6de0fd307690c8",
)

load(
    "@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl",
    "nixpkgs_git_repository",
    "nixpkgs_package",
)

nixpkgs_git_repository(
    name = "nixpkgs",
    revision = "1a95a36dbf15161d15ca2b2f7d5e3ccbb83093d3",
    sha256 = "df02202ad7c1c9d23ce89071e762ce8dd7c64e05244e38392ac5fcb24e893085",
)

nixpkgs_package(
    name = "ghc",
    attribute_path = "haskell.compiler.ghc844",
    repository = "@nixpkgs",
)

register_toolchains("//:ghc")
